version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Paris"
    reviewers:
      - "boul2gom"
    assignees:
      - "boul2gom"
    commit-message:
      prefix: "ðŸ”Œ [Github Actions] "
    target-branch: "develop"
    rebase-strategy: "auto"
